name: PR linting

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - edited
      - labeled
      - opened
      - reopened
      - synchronize
      - unlabeled

jobs:
  check-labels:
    name: Check labels
    runs-on: ubuntu-22.04
    steps:
      # cspell:ignore agilepathway
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          any_of:
            ğŸ› Bug,âœ¨ Feature,âš™ï¸ Enhancement,âš ï¸ Interface,â— Behavior,ğŸ“ Docs,ğŸ”¨
            Maintenance,ğŸ–±ï¸ DX
          none_of: Epic,ğŸ’« Good first issue
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  check-title:
    name: Check title
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: npm install @commitlint/config-conventional
        # cspell:ignore commitlint kode
      - uses: JulienKode/pull-request-name-linter-action@v0.5.0
